; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[env:fishbot]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    http://github.fishros.org/https://github.com/fishros/Esp32McpwmMotor.git
    http://github.fishros.org/https://github.com/fishros/Esp32PcntEncoder.git

build_flags =
    -I lib/ros_lib
; ROS1 rosserial headers are expected under lib/ros_lib
